"""add_users_table

Revision ID: 2236f72e9a3c
Revises: 38813d4c0823
Create Date: 2026-06-17 05:46:12.347186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2236f72e9a3c'
down_revision: Union[str, None] = '38813d4c0823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ACCOUNTANT', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Seed default users from environment variables
    import os
    import bcrypt

    admin_password = os.environ.get("ADMIN_PASSWORD", "admin123")
    accountant_password = os.environ.get("ACCOUNTANT_PASSWORD", "accountant1")
    auditor_password = os.environ.get("AUDITOR_PASSWORD", "auditor123")

    users_table = sa.table(
        'users',
        sa.column('username', sa.String),
        sa.column('hashed_password', sa.String),
        sa.column('role', sa.String),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(users_table, [
        {'username': 'admin', 'hashed_password': bcrypt.hashpw(admin_password.encode(), bcrypt.gensalt()).decode(), 'role': 'ADMIN', 'is_active': True},
        {'username': 'accountant', 'hashed_password': bcrypt.hashpw(accountant_password.encode(), bcrypt.gensalt()).decode(), 'role': 'ACCOUNTANT', 'is_active': True},
        {'username': 'auditor', 'hashed_password': bcrypt.hashpw(auditor_password.encode(), bcrypt.gensalt()).decode(), 'role': 'AUDITOR', 'is_active': True},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
