"""encrypt_llm_api_key

Revision ID: 38813d4c0823
Revises: dafd8249d0e8
Create Date: 2026-06-17 05:45:16.771183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38813d4c0823'
down_revision: Union[str, None] = 'dafd8249d0e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.alter_column('llm_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.alter_column('llm_api_key',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
