"""add_tax_and_closing_models

Revision ID: ac91122c688e
Revises: 2236f72e9a3c
Create Date: 2026-06-17 15:10:58.886023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac91122c688e'
down_revision: Union[str, None] = '2236f72e9a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.String(length=30), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rates_id'), 'tax_rates', ['id'], unique=False)
    op.create_index(op.f('ix_tax_rates_ledger_id'), 'tax_rates', ['ledger_id'], unique=False)
    op.create_table('closing_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=True),
    sa.Column('result_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closing_operations_id'), 'closing_operations', ['id'], unique=False)
    op.create_index(op.f('ix_closing_operations_ledger_id'), 'closing_operations', ['ledger_id'], unique=False)
    op.create_table('vat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('vat_type', sa.String(length=20), nullable=False),
    sa.Column('invoice_code', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('counterpart_name', sa.String(length=255), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_export', sa.Boolean(), nullable=True),
    sa.Column('export_amount_fob', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('export_currency', sa.String(length=10), nullable=True),
    sa.Column('export_rebate_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_records_id'), 'vat_records', ['id'], unique=False)
    op.create_index(op.f('ix_vat_records_ledger_id'), 'vat_records', ['ledger_id'], unique=False)
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('voucher_entries', sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('voucher_entries', sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_entries', 'vat_amount')
    op.drop_column('voucher_entries', 'vat_rate')
    op.drop_column('users', 'token_version')
    op.drop_index(op.f('ix_vat_records_ledger_id'), table_name='vat_records')
    op.drop_index(op.f('ix_vat_records_id'), table_name='vat_records')
    op.drop_table('vat_records')
    op.drop_index(op.f('ix_closing_operations_ledger_id'), table_name='closing_operations')
    op.drop_index(op.f('ix_closing_operations_id'), table_name='closing_operations')
    op.drop_table('closing_operations')
    op.drop_index(op.f('ix_tax_rates_ledger_id'), table_name='tax_rates')
    op.drop_index(op.f('ix_tax_rates_id'), table_name='tax_rates')
    op.drop_table('tax_rates')
    # ### end Alembic commands ###
