"""initial_schema

Revision ID: dafd8249d0e8
Revises: 
Create Date: 2026-06-16 23:22:21.109136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafd8249d0e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('start_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_api_key', sa.String(length=255), nullable=True),
    sa.Column('llm_base_url', sa.String(length=255), nullable=True),
    sa.Column('llm_model_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgers_id'), 'ledgers', ['id'], unique=False)
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='periodstatus'), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_periods_id'), 'accounting_periods', ['id'], unique=False)
    op.create_index(op.f('ix_accounting_periods_ledger_id'), 'accounting_periods', ['ledger_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'COST', 'PROFIT_LOSS', name='accounttype'), nullable=False),
    sa.Column('balance_direction', sa.Enum('DEBIT', 'CREDIT', name='accountdirection'), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_ledger_id'), 'accounts', ['ledger_id'], unique=False)
    op.create_table('business_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner_type', sa.Enum('CUSTOMER', 'VENDOR', 'BOTH', name='partnertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_partners_code'), 'business_partners', ['code'], unique=False)
    op.create_index(op.f('ix_business_partners_id'), 'business_partners', ['id'], unique=False)
    op.create_index(op.f('ix_business_partners_ledger_id'), 'business_partners', ['ledger_id'], unique=False)
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('salvage_value_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('expected_useful_months', sa.Integer(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_assets_asset_code'), 'fixed_assets', ['asset_code'], unique=False)
    op.create_index(op.f('ix_fixed_assets_id'), 'fixed_assets', ['id'], unique=False)
    op.create_index(op.f('ix_fixed_assets_ledger_id'), 'fixed_assets', ['ledger_id'], unique=False)
    op.create_table('voucher_number_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_number_counters_id'), 'voucher_number_counters', ['id'], unique=False)
    op.create_index(op.f('ix_voucher_number_counters_ledger_id'), 'voucher_number_counters', ['ledger_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('voucher_number', sa.String(length=50), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('attachments_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'POSTED', name='voucherstatus'), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index(op.f('ix_vouchers_ledger_id'), 'vouchers', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_number'), 'vouchers', ['voucher_number'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['accounting_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('original_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('related_voucher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['related_voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_original_documents_id'), 'original_documents', ['id'], unique=False)
    op.create_index(op.f('ix_original_documents_ledger_id'), 'original_documents', ['ledger_id'], unique=False)
    op.create_table('voucher_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='accountdirection'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['business_partners.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_entries_id'), 'voucher_entries', ['id'], unique=False)
    op.create_table('open_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('INVOICE', 'BANK_TXN', name='openitemtype'), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('txn_index', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counterpart_name', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unreconciled_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'CLEARED', name='openitemstatus'), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['original_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_items_id'), 'open_items', ['id'], unique=False)
    op.create_index(op.f('ix_open_items_ledger_id'), 'open_items', ['ledger_id'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('reconciled_date', sa.Date(), nullable=False),
    sa.Column('invoice_item_id', sa.Integer(), nullable=False),
    sa.Column('statement_item_id', sa.Integer(), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discrepancy_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discrepancy_type', sa.String(length=50), nullable=True),
    sa.Column('clearing_voucher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clearing_voucher_id'], ['vouchers.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['open_items.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['statement_item_id'], ['open_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_id'), 'reconciliation_records', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_ledger_id'), 'reconciliation_records', ['ledger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_records_ledger_id'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_id'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_open_items_ledger_id'), table_name='open_items')
    op.drop_index(op.f('ix_open_items_id'), table_name='open_items')
    op.drop_table('open_items')
    op.drop_index(op.f('ix_voucher_entries_id'), table_name='voucher_entries')
    op.drop_table('voucher_entries')
    op.drop_index(op.f('ix_original_documents_ledger_id'), table_name='original_documents')
    op.drop_index(op.f('ix_original_documents_id'), table_name='original_documents')
    op.drop_table('original_documents')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_vouchers_voucher_number'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_ledger_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_voucher_number_counters_ledger_id'), table_name='voucher_number_counters')
    op.drop_index(op.f('ix_voucher_number_counters_id'), table_name='voucher_number_counters')
    op.drop_table('voucher_number_counters')
    op.drop_index(op.f('ix_fixed_assets_ledger_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_id'), table_name='fixed_assets')
    op.drop_index(op.f('ix_fixed_assets_asset_code'), table_name='fixed_assets')
    op.drop_table('fixed_assets')
    op.drop_index(op.f('ix_business_partners_ledger_id'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_id'), table_name='business_partners')
    op.drop_index(op.f('ix_business_partners_code'), table_name='business_partners')
    op.drop_table('business_partners')
    op.drop_index(op.f('ix_accounts_ledger_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_accounting_periods_ledger_id'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_index(op.f('ix_ledgers_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
